### ISSUE TITLE
pantheios 1.0.1 218 beta compile error

### ISSUE THREAD

**Issue by silentspring** [synesissoftware/Pantheios#3]
Hi,

With pantheios 1.0.1 218 beta, I always get the following error at the beginning of the build:

make build
Ensuring all STLSoft C source files are in UNIX format
Ensuring all Pantheios - and bundled library - C source files are in UNIX format
make: *** No rule to make target ../../include/pantheios/internal/generated/log_functions.inl', needed bycore.api.exitprocess.mt.debug.o'. Stop.

It looks the `../../include/pantheios/internal/generated/log_functions.inl' indeed is not there.
Is it pregenerated by some other build command?

Thanks

**Comment by glennra** [comment]
I got the same error trying to build the 218 beta that I downloaded from sourceforge using vc14.x64. 
Worked around it by getting the file include/pantheios/internal/generated/log_functions.c from beta214 and copying it to include/pantheios/generated/log_functions.inl and adjusting the path names in the makefile and src/core/auto.cpp. This allows the library to build but some examples and tests still fail.
The other workaround is to download the zip of the master branch from here (github), which has all the required files included.

**Comment by synesissoftware** [comment]
Don't really understand this one. There's just been a [new release some moments ago](https://github.com/synesissoftware/Pantheios/releases) and there'll be lots of activity over the coming months. Please let us know if this recurs (or any other issues). Closing this one now.
