### ISSUE TITLE
ms vs 14 build failed 

### ISSUE THREAD

**Issue by nneesshh** [synesissoftware/Pantheios#4]
The error is:

D:\dd\sdk\support\pantheios\Pantheios-master\build\vc14.x64>nmake build

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl    -nologo -c -W4 -wd4800 -wd4996 -WX     -EHsc -GR -MTd -D_DEBUG -Zi
 -Fd.\core.api.exitprocess.mt.debug.vc14.x64.pdb    -DWIN64   -DSHWILD_QUALITY_N
O_USE_XCOVER -DPANTHEIOS_NO_AUTO_INIT    -I..\..\include      -I"D:\dd\sdk\suppo
rt\pantheios\stlsoft-1.9.124\include"   -Fo.\core.api.exitprocess.mt.debug.obj .
.\..\src\core\api.exitprocess.cpp
api.exitprocess.cpp
D:\dd\sdk\support\pantheios\stlsoft-1.9.124\include\stlsoft/stlsoft.h(1287): fat
al error C1083: Cannot open include file: 'stddef.h': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\bin\cl.EXE"' : return code '0x2'
Stop.

I don't know why, please help me, thanks

**Comment by ljestrada** [comment]
@nneesshh 
Are you using the proper Command Prompt?

Visual Studio installs a Developer Command Prompt that inserts the proper paths for the include files and libraries, etc.

For example, in Visual Studio 2017 I have a **Developer Command Prompt for VS 2017** 

Hope it helps.

**Comment by synesissoftware** [comment]
Yeah, that looks like [ljestrada](https://github.com/ljestrada) has the right answer

> @nneesshh
> Are you using the proper Command Prompt?
> 
> Visual Studio installs a Developer Command Prompt that inserts the proper paths for the include files and libraries, etc.
> 
> For example, in Visual Studio 2017 I have a **Developer Command Prompt for VS 2017**
> 
> Hope it helps.
